// <auto-generated />
namespace Gazorpgazorpfridge.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class whyamigrationforeverypull : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(whyamigrationforeverypull));
        
        string IMigrationMetadata.Id
        {
            get { return "201711111713207_why-a-migration-for-every-pull"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
