// <auto-generated />
namespace Gazorpgazorpfridge.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Added_user_reference_to_receta : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_user_reference_to_receta));
        
        string IMigrationMetadata.Id
        {
            get { return "201711122153597_Added_user_reference_to_receta"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
