// <auto-generated />
namespace Gazorpgazorpfridge.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Canasta_Foreign : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Canasta_Foreign));
        
        string IMigrationMetadata.Id
        {
            get { return "201711131837072_Canasta_Foreign"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
